doctrine_mongodb:
    auto_generate_proxy_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'   # ex: mongodb://localhost:27017
            options: { }
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                General:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/General/Infrastructure/Document'
                    prefix: 'App\General\Infrastructure\Document'
                    alias: GeneralDocument
                Log:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Log/Infrastructure/Document'
                    prefix: 'App\Log\Infrastructure\Document'
                    alias: LogDocument
                LogLoginFailure:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Log/Infrastructure/Document'
                    prefix: 'App\Log\Infrastructure\Document'
                    alias: LogLoginFailureDocument
                Messenger:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Messenger/Infrastructure/Document'
                    prefix: 'App\Messenger\Infrastructure\Document'
                    alias: MessengerDocument
